In [46]:
import pandas as pd
import numpy as np

In [47]:
fpath = 'C:\\Users\\gg00642\\OneDrive - University of Surrey\\Desktop\\Actigraphy Sara'

In [48]:
df = pd.read_excel(fpath + '\\5.0_database_variables.xlsx')

In [49]:
#extracting the columns of interest
sleep_period= df[['start_datetime','end_datetime']]

In [50]:
sleep_period.head()

       start_datetime        end_datetime
0 2022-09-21 22:08:00 2022-09-22 06:56:00
1 2022-09-22 20:28:00 2022-09-23 06:49:00
2 2022-09-23 21:06:00 2022-09-24 06:48:00
3 2022-09-24 22:15:00 2022-09-25 08:08:00
4 2022-09-25 22:43:00 2022-09-26 06:54:00

In [51]:
sleep_scoring = pd.read_csv(fpath + '\\roenneberg_thr.csv', index_col=0)

In [52]:
sleep_scoring.reset_index(inplace=True) #resetting the dataframe index to start from 0

In [53]:
#rename the columns
sleep_scoring.columns = ['datetime', 'score']

In [54]:
sleep_scoring.head()

              datetime  score
0  2022-09-21 16:05:00      0
1  2022-09-21 16:05:30      0
2  2022-09-21 16:06:00      0
3  2022-09-21 16:06:30      0
4  2022-09-21 16:07:00      0

In [55]:
#save the sleep period as list and mantaing the same format as the sleep scoring
sleep_period_list = []
for i in range(len(sleep_period)):
    sleep_period_list.append([sleep_period['start_datetime'][i], sleep_period['end_datetime'][i]])

In [58]:
sleep_period_list

[[Timestamp('2022-09-21 22:08:00'), Timestamp('2022-09-22 06:56:00')],
 [Timestamp('2022-09-22 20:28:00'), Timestamp('2022-09-23 06:49:00')],
 [Timestamp('2022-09-23 21:06:00'), Timestamp('2022-09-24 06:48:00')],
 [Timestamp('2022-09-24 22:15:00'), Timestamp('2022-09-25 08:08:00')],
 [Timestamp('2022-09-25 22:43:00'), Timestamp('2022-09-26 06:54:00')],
 [Timestamp('2022-09-26 20:00:00'), Timestamp('2022-09-27 06:49:00')],
 [Timestamp('2022-09-27 22:03:00'), Timestamp('2022-09-28 06:43:00')],
 [Timestamp('2022-09-29 01:19:00'), Timestamp('2022-09-29 06:44:00')],
 [Timestamp('2022-09-29 21:04:00'), Timestamp('2022-09-30 07:03:00')],
 [Timestamp('2022-09-30 22:21:00'), Timestamp('2022-10-01 09:21:00')],
 [Timestamp('2022-10-01 22:32:00'), Timestamp('2022-10-02 08:36:00')],
 [Timestamp('2022-10-03 00:44:00'), Timestamp('2022-10-03 06:43:00')],
 [Timestamp('2022-10-03 23:00:00'), Timestamp('2022-10-04 07:13:00')],
 [Timestamp('2022-10-05 00:08:00'), Timestamp('2022-10-05 04:28:00')],
 [Timestamp('2022-10-05 21:11:00'), Timestamp('2022-10-06 05:18:00')],
 [Timestamp('2022-10-06 22:09:00'), Timestamp('2022-10-07 06:58:00')],
 [Timestamp('2022-10-07 20:58:00'), Timestamp('2022-10-08 05:49:00')],
 [Timestamp('2022-10-08 22:46:00'), Timestamp('2022-10-09 07:24:00')],
 [Timestamp('2022-10-09 23:59:00'), Timestamp('2022-10-10 06:42:00')],
 [Timestamp('2022-10-10 21:19:00'), Timestamp('2022-10-11 06:51:00')],
 [Timestamp('2022-10-11 21:27:00'), Timestamp('2022-10-12 07:53:00')],
 [Timestamp('2022-10-13 00:14:00'), Timestamp('2022-10-13 06:57:00')],
 [Timestamp('2022-10-14 01:01:00'), Timestamp('2022-10-14 06:59:00')],
 [Timestamp('2022-10-14 23:10:00'), Timestamp('2022-10-15 08:22:00')],
 [Timestamp('2022-10-15 23:43:00'), Timestamp('2022-10-16 08:03:00')],
 [Timestamp('2022-10-16 20:50:00'), Timestamp('2022-10-17 07:03:00')],
 [Timestamp('2022-10-17 22:01:00'), Timestamp('2022-10-18 06:50:00')],
 [Timestamp('2022-10-18 21:19:00'), Timestamp('2022-10-19 07:30:00')],
 [Timestamp('2022-10-19 20:17:00'), Timestamp('2022-10-20 07:10:00')],
 [Timestamp('2022-10-21 00:31:00'), Timestamp('2022-10-21 07:42:00')],
 [Timestamp('2022-10-21 23:16:00'), Timestamp('2022-10-22 08:20:00')],
 [Timestamp('2022-10-23 00:26:00'), Timestamp('2022-10-23 06:45:00')],
 [Timestamp('2022-10-23 22:09:00'), Timestamp('2022-10-24 07:01:00')],
 [Timestamp('2022-10-24 21:39:00'), Timestamp('2022-10-25 06:58:00')],
 [Timestamp('2022-10-25 21:58:00'), Timestamp('2022-10-26 07:06:00')],
 [Timestamp('2022-10-26 20:59:00'), Timestamp('2022-10-27 06:47:00')],
 [Timestamp('2022-10-27 23:11:00'), Timestamp('2022-10-28 07:28:00')],
 [Timestamp('2022-10-28 20:38:00'), Timestamp('2022-10-29 07:45:00')],
 [Timestamp('2022-10-29 22:24:00'), Timestamp('2022-10-30 07:28:00')],
 [Timestamp('2022-10-30 22:49:00'), Timestamp('2022-10-31 06:45:00')],
 [Timestamp('2022-10-31 23:16:00'), Timestamp('2022-11-01 08:17:00')],
 [Timestamp('2022-11-01 19:47:00'), Timestamp('2022-11-02 06:55:00')],
 [Timestamp('2022-11-02 23:04:00'), Timestamp('2022-11-03 06:51:00')],
 [Timestamp('2022-11-03 20:36:00'), Timestamp('2022-11-04 06:18:00')],
 [Timestamp('2022-11-04 22:28:00'), Timestamp('2022-11-05 08:16:00')],
 [Timestamp('2022-11-06 01:05:00'), Timestamp('2022-11-06 09:46:00')],
 [Timestamp('2022-11-06 22:55:00'), Timestamp('2022-11-07 06:57:00')],
 [Timestamp('2022-11-07 22:32:00'), Timestamp('2022-11-08 07:07:00')],
 [Timestamp('2022-11-08 22:04:00'), Timestamp('2022-11-09 06:41:00')],
 [Timestamp('2022-11-09 20:26:00'), Timestamp('2022-11-10 06:48:00')],
 [Timestamp('2022-11-10 20:28:00'), Timestamp('2022-11-11 06:50:00')],
 [Timestamp('2022-11-11 22:11:00'), Timestamp('2022-11-12 09:03:00')],
 [Timestamp('2022-11-12 22:42:00'), Timestamp('2022-11-13 07:52:00')],
 [Timestamp('2022-11-14 00:12:00'), Timestamp('2022-11-14 08:04:00')],
 [Timestamp('2022-11-14 21:11:00'), Timestamp('2022-11-15 07:02:00')],
 [Timestamp('2022-11-15 21:19:00'), Timestamp('2022-11-16 06:47:00')],
 [Timestamp('2022-11-16 23:30:00'), Timestamp('2022-11-17 07:22:00')],
 [Timestamp('2022-11-17 23:12:00'), Timestamp('2022-11-18 06:42:00')],
 [Timestamp('2022-11-18 21:09:00'), Timestamp('2022-11-19 06:48:00')],
 [Timestamp('2022-11-19 23:42:00'), Timestamp('2022-11-20 09:58:00')],
 [Timestamp('2022-11-20 22:10:00'), Timestamp('2022-11-21 07:00:00')],
 [Timestamp('2022-11-21 19:32:00'), Timestamp('2022-11-22 06:57:00')],
 [Timestamp('2022-11-22 20:30:00'), Timestamp('2022-11-23 06:57:00')],
 [Timestamp('2022-11-23 20:23:00'), Timestamp('2022-11-24 06:57:00')],
 [Timestamp('2022-11-24 22:34:00'), Timestamp('2022-11-25 06:49:00')],
 [Timestamp('2022-11-26 09:09:00'), Timestamp('2022-11-26 13:21:00')],
 [Timestamp('2022-11-26 20:23:00'), Timestamp('2022-11-27 05:51:00')],
 [Timestamp('2022-11-28 00:02:00'), Timestamp('2022-11-28 06:46:00')],
 [Timestamp('2022-11-28 22:33:00'), Timestamp('2022-11-29 06:46:00')],
 [Timestamp('2022-11-29 21:45:00'), Timestamp('2022-11-30 07:10:00')],
 [Timestamp('2022-11-30 23:48:00'), Timestamp('2022-12-01 06:43:00')],
 [Timestamp('2022-12-01 22:58:00'), Timestamp('2022-12-02 06:58:00')],
 [Timestamp('2022-12-02 22:20:00'), Timestamp('2022-12-03 09:16:00')],
 [Timestamp('2022-12-03 21:29:00'), Timestamp('2022-12-04 07:11:00')],
 [Timestamp('2022-12-04 21:10:00'), Timestamp('2022-12-05 06:47:00')],
 [Timestamp('2022-12-05 23:15:00'), Timestamp('2022-12-06 06:42:00')],
 [Timestamp('2022-12-06 23:11:00'), Timestamp('2022-12-07 06:51:00')],
 [Timestamp('2022-12-07 21:39:00'), Timestamp('2022-12-08 06:49:00')],
 [Timestamp('2022-12-08 21:43:00'), Timestamp('2022-12-09 07:45:00')],
 [Timestamp('2022-12-09 23:51:00'), Timestamp('2022-12-10 07:57:00')],
 [Timestamp('2022-12-10 21:56:00'), Timestamp('2022-12-11 08:20:00')],
 [Timestamp('2022-12-11 22:17:00'), Timestamp('2022-12-12 06:41:00')],
 [Timestamp('2022-12-12 20:57:00'), Timestamp('2022-12-13 06:39:00')],
 [Timestamp('2022-12-13 22:53:00'), Timestamp('2022-12-14 06:43:00')],
 [Timestamp('2022-12-14 22:48:00'), Timestamp('2022-12-15 06:51:00')],
 [Timestamp('2022-12-15 22:12:00'), Timestamp('2022-12-16 08:16:00')],
 [Timestamp('2022-12-16 22:02:00'), Timestamp('2022-12-17 08:48:00')],
 [Timestamp('2022-12-17 23:43:00'), Timestamp('2022-12-18 06:42:00')],
 [Timestamp('2022-12-19 00:32:00'), Timestamp('2022-12-19 06:49:00')],
 [Timestamp('2022-12-19 23:37:00'), Timestamp('2022-12-20 06:53:00')],
 [Timestamp('2022-12-20 18:52:00'), Timestamp('2022-12-21 05:02:00')],
 [Timestamp('2022-12-21 19:40:00'), Timestamp('2022-12-22 06:46:00')],
 [Timestamp('2022-12-23 02:04:00'), Timestamp('2022-12-23 07:11:00')],
 [Timestamp('2022-12-24 00:58:00'), Timestamp('2022-12-24 10:17:00')],
 [Timestamp('2022-12-24 20:53:00'), Timestamp('2022-12-25 06:57:00')],
 [Timestamp('2022-12-25 22:46:00'), Timestamp('2022-12-26 08:50:00')],
 [Timestamp('2022-12-26 22:17:00'), Timestamp('2022-12-27 06:56:00')],
 [Timestamp('2022-12-27 22:16:00'), Timestamp('2022-12-28 06:50:00')],
 [Timestamp('2022-12-29 22:05:00'), Timestamp('2022-12-30 07:03:00')],
 [Timestamp('2022-12-30 21:51:00'), Timestamp('2022-12-31 09:06:00')],
 [Timestamp('2022-12-31 23:22:00'), Timestamp('2023-01-01 07:24:00')],
 [Timestamp('2023-01-01 22:15:00'), Timestamp('2023-01-02 08:51:00')],
 [Timestamp('2023-01-02 23:14:00'), Timestamp('2023-01-03 09:01:00')],
 [Timestamp('2023-01-03 23:37:00'), Timestamp('2023-01-04 07:43:00')],
 [Timestamp('2023-01-04 22:47:00'), Timestamp('2023-01-05 08:24:00')],
 [Timestamp('2023-01-05 22:56:00'), Timestamp('2023-01-06 08:32:00')],
 [Timestamp('2023-01-07 01:07:00'), Timestamp('2023-01-07 09:01:00')],
 [Timestamp('2023-01-07 22:52:00'), Timestamp('2023-01-08 08:15:00')],
 [Timestamp('2023-01-08 21:50:00'), Timestamp('2023-01-09 06:37:00')],
 [Timestamp('2023-01-09 20:38:00'), Timestamp('2023-01-10 06:47:00')],
 [Timestamp('2023-01-10 21:12:00'), Timestamp('2023-01-11 06:41:00')],
 [Timestamp('2023-01-11 19:40:00'), Timestamp('2023-01-12 06:51:00')],
 [Timestamp('2023-01-12 22:51:00'), Timestamp('2023-01-13 06:53:00')],
 [Timestamp('2023-01-13 17:53:00'), Timestamp('2023-01-14 05:18:00')],
 [Timestamp('2023-01-14 21:53:00'), Timestamp('2023-01-15 08:34:00')],
 [Timestamp('2023-01-15 23:18:00'), Timestamp('2023-01-16 06:59:00')],
 [Timestamp('2023-01-16 20:39:00'), Timestamp('2023-01-17 06:41:00')],
 [Timestamp('2023-01-17 21:25:00'), Timestamp('2023-01-18 06:59:00')],
 [Timestamp('2023-01-18 22:41:00'), Timestamp('2023-01-19 07:00:00')],
 [Timestamp('2023-01-20 00:14:00'), Timestamp('2023-01-20 07:12:00')],
 [Timestamp('2023-01-20 22:36:00'), Timestamp('2023-01-21 06:50:00')],
 [Timestamp('2023-01-21 21:44:00'), Timestamp('2023-01-22 08:00:00')],
 [Timestamp('2023-01-23 02:33:00'), Timestamp('2023-01-23 06:49:00')],
 [Timestamp('2023-01-23 19:58:00'), Timestamp('2023-01-24 07:03:00')],
 [Timestamp('2023-01-24 20:15:00'), Timestamp('2023-01-25 07:12:00')],
 [Timestamp('2023-01-25 22:14:00'), Timestamp('2023-01-26 07:04:00')],
 [Timestamp('2023-01-26 22:23:00'), Timestamp('2023-01-27 09:01:00')],
 [Timestamp('2023-01-28 03:49:00'), Timestamp('2023-01-28 07:07:00')],
 [Timestamp('2023-01-28 23:52:00'), Timestamp('2023-01-29 10:24:00')],
 [Timestamp('2023-01-29 22:47:00'), Timestamp('2023-01-30 06:54:00')],
 [Timestamp('2023-01-30 21:29:00'), Timestamp('2023-01-31 06:49:00')],
 [Timestamp('2023-01-31 22:03:00'), Timestamp('2023-02-01 07:02:00')],
 [Timestamp('2023-02-01 22:54:00'), Timestamp('2023-02-02 07:10:00')],
 [Timestamp('2023-02-02 21:11:00'), Timestamp('2023-02-03 07:09:00')],
 [Timestamp('2023-02-03 22:31:00'), Timestamp('2023-02-04 08:48:00')],
 [Timestamp('2023-02-04 22:22:00'), Timestamp('2023-02-05 08:12:00')],
 [Timestamp('2023-02-05 21:45:00'), Timestamp('2023-02-06 06:32:00')],
 [Timestamp('2023-02-06 22:15:00'), Timestamp('2023-02-07 06:58:00')],
 [Timestamp('2023-02-07 20:20:00'), Timestamp('2023-02-08 06:54:00')],
 [Timestamp('2023-02-08 22:03:00'), Timestamp('2023-02-09 06:15:00')],
 [Timestamp('2023-02-09 21:48:00'), Timestamp('2023-02-10 07:15:00')],
 [Timestamp('2023-02-10 21:15:00'), Timestamp('2023-02-11 08:05:00')],
 [Timestamp('2023-02-12 00:36:00'), Timestamp('2023-02-12 08:13:00')],
 [Timestamp('2023-02-12 22:58:00'), Timestamp('2023-02-13 06:46:00')],
 [Timestamp('2023-02-13 23:16:00'), Timestamp('2023-02-14 06:40:00')],
 [Timestamp('2023-02-14 23:53:00'), Timestamp('2023-02-15 07:29:00')],
 [Timestamp('2023-02-15 23:34:00'), Timestamp('2023-02-16 07:34:00')],
 [Timestamp('2023-02-16 21:28:00'), Timestamp('2023-02-17 07:05:00')],
 [Timestamp('2023-02-17 22:41:00'), Timestamp('2023-02-18 09:56:00')],
 [Timestamp('2023-02-18 22:59:00'), Timestamp('2023-02-19 06:47:00')],
 [Timestamp('2023-02-19 22:46:00'), Timestamp('2023-02-20 06:52:00')],
 [Timestamp('2023-02-20 21:17:00'), Timestamp('2023-02-21 06:42:00')],
 [Timestamp('2023-02-21 21:31:00'), Timestamp('2023-02-22 06:57:00')],
 [Timestamp('2023-02-22 21:47:00'), Timestamp('2023-02-23 07:44:00')],
 [Timestamp('2023-02-23 22:45:00'), Timestamp('2023-02-24 09:34:00')],
 [Timestamp('2023-02-24 23:25:00'), Timestamp('2023-02-25 03:30:00')],
 [Timestamp('2023-02-26 00:30:00'), Timestamp('2023-02-26 08:47:00')],
 [Timestamp('2023-02-26 22:14:00'), Timestamp('2023-02-27 07:15:00')],
 [Timestamp('2023-02-27 20:09:00'), Timestamp('2023-02-28 07:02:00')],
 [Timestamp('2023-02-28 21:03:00'), Timestamp('2023-03-01 06:55:00')],
 [Timestamp('2023-03-01 20:39:00'), Timestamp('2023-03-02 06:31:00')],
 [Timestamp('2023-03-02 22:12:00'), Timestamp('2023-03-03 06:57:00')],
 [Timestamp('2023-03-03 21:49:00'), Timestamp('2023-03-04 08:35:00')],
 [Timestamp('2023-04-18 21:10:00'), Timestamp('2023-04-19 05:39:00')],
 [Timestamp('2023-04-19 23:09:00'), Timestamp('2023-04-20 07:54:00')],
 [Timestamp('2023-04-21 00:13:00'), Timestamp('2023-04-21 06:58:00')],
 [Timestamp('2023-04-22 00:50:00'), Timestamp('2023-04-22 09:53:00')],
 [Timestamp('2023-04-22 22:26:00'), Timestamp('2023-04-23 08:40:00')],
 [Timestamp('2023-04-23 21:32:00'), Timestamp('2023-04-24 06:54:00')],
 [Timestamp('2023-04-24 23:21:00'), Timestamp('2023-04-25 07:12:00')],
 [Timestamp('2023-04-25 20:52:00'), Timestamp('2023-04-26 07:13:00')],
 [Timestamp('2023-04-26 23:45:00'), Timestamp('2023-04-27 07:06:00')],
 [Timestamp('2023-04-27 22:32:00'), Timestamp('2023-04-28 06:59:00')],
 [Timestamp('2023-04-28 21:26:00'), Timestamp('2023-04-29 05:55:00')],
 [Timestamp('2023-04-30 00:17:00'), Timestamp('2023-04-30 06:46:00')],
 [Timestamp('2023-04-30 22:45:00'), Timestamp('2023-05-01 09:08:00')],
 [Timestamp('2023-05-01 23:46:00'), Timestamp('2023-05-02 06:50:00')],
 [Timestamp('2023-05-02 19:48:00'), Timestamp('2023-05-03 06:49:00')],
 [Timestamp('2023-05-03 20:38:00'), Timestamp('2023-05-04 06:10:00')],
 [Timestamp('2023-05-04 21:44:00'), Timestamp('2023-05-05 06:48:00')],
 [Timestamp('2023-05-05 23:46:00'), Timestamp('2023-05-06 07:50:00')],
 [Timestamp('2023-05-06 21:26:00'), Timestamp('2023-05-07 08:32:00')],
 [Timestamp('2023-05-07 22:14:00'), Timestamp('2023-05-08 07:25:00')],
 [Timestamp('2023-05-08 21:52:00'), Timestamp('2023-05-09 06:52:00')],
 [Timestamp('2023-05-09 19:01:00'), Timestamp('2023-05-10 06:19:00')],
 [Timestamp('2023-05-11 00:20:00'), Timestamp('2023-05-11 06:59:00')],
 [Timestamp('2023-05-11 21:54:00'), Timestamp('2023-05-12 07:33:00')],
 [Timestamp('2023-05-12 20:54:00'), Timestamp('2023-05-13 05:37:00')],
 [Timestamp('2023-05-13 21:32:00'), Timestamp('2023-05-14 06:36:00')],
 [Timestamp('2023-05-15 22:43:00'), Timestamp('2023-05-16 06:33:00')],
 [Timestamp('2023-06-30 00:15:00'), Timestamp('2023-06-30 06:57:00')],
 [Timestamp('2023-06-30 22:31:00'), Timestamp('2023-07-01 06:27:00')],
 [Timestamp('2023-07-01 23:00:00'), Timestamp('2023-07-02 07:33:00')],
 [Timestamp('2023-07-02 22:55:00'), Timestamp('2023-07-03 06:21:00')],
 [Timestamp('2023-07-03 20:41:00'), Timestamp('2023-07-04 06:44:00')],
 [Timestamp('2023-07-04 22:21:00'), Timestamp('2023-07-05 06:55:00')],
 [Timestamp('2023-07-05 21:53:00'), Timestamp('2023-07-06 06:48:00')],
 [Timestamp('2023-07-06 19:09:00'), Timestamp('2023-07-07 06:25:00')],
 [Timestamp('2023-07-07 19:27:00'), Timestamp('2023-07-08 06:08:00')],
 [Timestamp('2023-07-08 21:12:00'), Timestamp('2023-07-09 06:45:00')],
 [Timestamp('2023-07-09 22:38:00'), Timestamp('2023-07-10 06:50:00')],
 [Timestamp('2023-07-10 20:23:00'), Timestamp('2023-07-11 06:43:00')],
 [Timestamp('2023-07-11 20:26:00'), Timestamp('2023-07-12 06:55:00')],
 [Timestamp('2023-07-12 19:42:00'), Timestamp('2023-07-13 06:26:00')],
 [Timestamp('2023-07-13 23:45:00'), Timestamp('2023-07-14 07:53:00')],
 [Timestamp('2023-07-14 19:59:00'), Timestamp('2023-07-15 04:16:00')],
 [Timestamp('2023-07-15 21:20:00'), Timestamp('2023-07-16 07:48:00')],
 [Timestamp('2023-07-16 23:42:00'), Timestamp('2023-07-17 08:46:00')],
 [Timestamp('2023-07-17 23:44:00'), Timestamp('2023-07-18 08:48:00')],
 [Timestamp('2023-07-18 23:43:00'), Timestamp('2023-07-19 08:42:00')],
 [Timestamp('2023-07-19 22:54:00'), Timestamp('2023-07-20 06:50:00')],
 [Timestamp('2023-07-20 22:45:00'), Timestamp('2023-07-21 08:21:00')],
 [Timestamp('2023-07-22 00:41:00'), Timestamp('2023-07-22 08:58:00')],
 [Timestamp('2023-07-22 22:22:00'), Timestamp('2023-07-23 09:29:00')],
 [Timestamp('2023-07-23 23:31:00'), Timestamp('2023-07-24 08:12:00')],
 [Timestamp('2023-07-25 01:56:00'), Timestamp('2023-07-25 09:40:00')],
 [Timestamp('2023-07-25 22:18:00'), Timestamp('2023-07-26 09:05:00')],
 [Timestamp('2023-07-26 22:38:00'), Timestamp('2023-07-27 09:00:00')],
 [Timestamp('2023-07-27 22:45:00'), Timestamp('2023-07-28 08:26:00')],
 [Timestamp('2023-07-28 21:20:00'), Timestamp('2023-07-29 05:48:00')],
 [Timestamp('2023-07-30 00:47:00'), Timestamp('2023-07-30 10:33:00')],
 [Timestamp('2023-07-30 22:34:00'), Timestamp('2023-07-31 08:11:00')],
 [Timestamp('2023-08-16 23:11:00'), Timestamp('2023-08-17 07:11:00')],
 [Timestamp('2023-08-17 20:27:00'), Timestamp('2023-08-18 07:10:00')],
 [Timestamp('2023-08-22 23:11:00'), Timestamp('2023-08-23 06:58:00')],
 [Timestamp('2023-08-23 22:49:00'), Timestamp('2023-08-24 07:00:00')],
 [Timestamp('2023-08-24 22:07:00'), Timestamp('2023-08-25 06:52:00')],
 [Timestamp('2023-08-25 20:53:00'), Timestamp('2023-08-26 06:48:00')],
 [Timestamp('2023-08-26 23:09:00'), Timestamp('2023-08-27 09:12:00')],
 [Timestamp('2023-08-27 22:48:00'), Timestamp('2023-08-28 06:33:00')],
 [Timestamp('2023-08-28 21:44:00'), Timestamp('2023-08-29 07:02:00')],
 [Timestamp('2023-08-29 23:04:00'), Timestamp('2023-08-30 07:04:00')],
 [Timestamp('2023-08-30 21:26:00'), Timestamp('2023-08-31 06:31:00')],
 [Timestamp('2023-08-31 21:49:00'), Timestamp('2023-09-01 06:44:00')],
 [Timestamp('2023-09-02 00:00:00'), Timestamp('2023-09-02 08:34:00')],
 [Timestamp('2023-09-02 22:36:00'), Timestamp('2023-09-03 05:33:00')],
 [Timestamp('2023-09-03 22:36:00'), Timestamp('2023-09-04 06:40:00')],
 [Timestamp('2023-09-04 21:59:00'), Timestamp('2023-09-05 06:46:00')],
 [Timestamp('2023-09-05 22:05:00'), Timestamp('2023-09-06 06:44:00')],
 [Timestamp('2023-09-06 21:32:00'), Timestamp('2023-09-07 06:43:00')],
 [Timestamp('2023-09-07 23:15:00'), Timestamp('2023-09-08 06:33:00')],
 [Timestamp('2023-09-08 23:12:00'), Timestamp('2023-09-09 08:08:00')],
 [Timestamp('2023-09-09 23:45:00'), Timestamp('2023-09-10 07:47:00')],
 [Timestamp('2023-09-10 22:52:00'), Timestamp('2023-09-11 07:03:00')],
 [Timestamp('2023-09-11 19:58:00'), Timestamp('2023-09-12 06:36:00')],
 [Timestamp('2023-09-12 22:15:00'), Timestamp('2023-09-13 07:13:00')],
 [Timestamp('2023-09-13 19:23:00'), Timestamp('2023-09-14 06:39:00')],
 [Timestamp('2023-09-14 18:38:00'), Timestamp('2023-09-15 06:46:00')],
 [Timestamp('2023-09-15 23:03:00'), Timestamp('2023-09-16 09:07:00')],
 [Timestamp('2023-09-16 22:54:00'), Timestamp('2023-09-17 06:43:00')],
 [Timestamp('2023-09-17 23:07:00'), Timestamp('2023-09-18 06:55:00')],
 [Timestamp('2023-09-18 20:38:00'), Timestamp('2023-09-19 06:45:00')],
 [Timestamp('2023-09-19 22:54:00'), Timestamp('2023-09-20 07:15:00')],
 [Timestamp('2023-09-20 20:19:00'), Timestamp('2023-09-21 06:53:00')],
 [Timestamp('2023-09-21 23:46:00'), Timestamp('2023-09-22 07:05:00')],
 [Timestamp('2023-09-22 22:40:00'), Timestamp('2023-09-23 09:01:00')],
 [Timestamp('2023-09-24 01:02:00'), Timestamp('2023-09-24 09:44:00')],
 [Timestamp('2023-09-24 22:00:00'), Timestamp('2023-09-25 08:01:00')],
 [Timestamp('2023-09-25 23:25:00'), Timestamp('2023-09-26 06:44:00')],
 [Timestamp('2023-09-26 21:57:00'), Timestamp('2023-09-27 06:44:00')],
 [Timestamp('2023-09-27 23:06:00'), Timestamp('2023-09-28 07:03:00')],
 [Timestamp('2023-09-28 22:34:00'), Timestamp('2023-09-29 07:50:00')],
 [Timestamp('2023-09-30 00:02:00'), Timestamp('2023-09-30 08:28:00')],
 [Timestamp('2023-10-01 01:49:00'), Timestamp('2023-10-01 09:01:00')],
 [Timestamp('2023-10-01 23:12:00'), Timestamp('2023-10-02 06:44:00')],
 [Timestamp('2023-10-02 21:29:00'), Timestamp('2023-10-03 06:40:00')],
 [Timestamp('2023-10-03 20:32:00'), Timestamp('2023-10-04 06:59:00')],
 [Timestamp('2023-10-04 20:32:00'), Timestamp('2023-10-05 06:42:00')],
 [Timestamp('2023-10-05 19:34:00'), Timestamp('2023-10-06 06:22:00')],
 [Timestamp('2023-10-06 22:42:00'), Timestamp('2023-10-07 09:25:00')],
 [Timestamp('2023-10-07 20:58:00'), Timestamp('2023-10-08 08:13:00')],
 [Timestamp('2023-10-08 23:19:00'), Timestamp('2023-10-09 06:42:00')],
 [Timestamp('2023-10-09 19:24:00'), Timestamp('2023-10-10 06:42:00')],
 [Timestamp('2023-10-10 23:13:00'), Timestamp('2023-10-11 06:47:00')],
 [Timestamp('2023-10-11 20:41:00'), Timestamp('2023-10-12 06:41:00')],
 [Timestamp('2023-10-12 22:00:00'), Timestamp('2023-10-13 07:26:00')],
 [Timestamp('2023-10-13 21:48:00'), Timestamp('2023-10-14 08:41:00')],
 [Timestamp('2023-10-14 22:38:00'), Timestamp('2023-10-15 06:45:00')],
 [Timestamp('2023-10-15 23:01:00'), Timestamp('2023-10-16 06:54:00')],
 [Timestamp('2023-10-16 21:07:00'), Timestamp('2023-10-17 07:03:00')],
 [Timestamp('2023-10-17 20:57:00'), Timestamp('2023-10-18 06:58:00')],

In [60]:
#save the sleep_scoring as list and mantaing the same format as the sleep scoring
sleep_scoring_list = []
for i in range(len(sleep_scoring)):
    sleep_scoring_list.append([sleep_scoring['datetime'][i], sleep_scoring['score'][i]])

In [61]:
sleep_scoring_list

[[Timestamp('2022-09-21 16:05:00'), 0],
 [Timestamp('2022-09-21 16:05:30'), 0],
 [Timestamp('2022-09-21 16:06:00'), 0],
 [Timestamp('2022-09-21 16:06:30'), 0],
 [Timestamp('2022-09-21 16:07:00'), 0],
 [Timestamp('2022-09-21 16:07:30'), 0],
 [Timestamp('2022-09-21 16:08:00'), 0],
 [Timestamp('2022-09-21 16:08:30'), 0],
 [Timestamp('2022-09-21 16:09:00'), 0],
 [Timestamp('2022-09-21 16:09:30'), 0],
 [Timestamp('2022-09-21 16:10:00'), 0],
 [Timestamp('2022-09-21 16:10:30'), 0],
 [Timestamp('2022-09-21 16:11:00'), 0],
 [Timestamp('2022-09-21 16:11:30'), 0],
 [Timestamp('2022-09-21 16:12:00'), 0],
 [Timestamp('2022-09-21 16:12:30'), 0],
 [Timestamp('2022-09-21 16:13:00'), 0],
 [Timestamp('2022-09-21 16:13:30'), 0],
 [Timestamp('2022-09-21 16:14:00'), 0],
 [Timestamp('2022-09-21 16:14:30'), 0],
 [Timestamp('2022-09-21 16:15:00'), 0],
 [Timestamp('2022-09-21 16:15:30'), 0],
 [Timestamp('2022-09-21 16:16:00'), 0],
 [Timestamp('2022-09-21 16:16:30'), 0],
 [Timestamp('2022-09-21 16:17:00'), 0],
 [Timestamp('2022-09-21 16:17:30'), 0],
 [Timestamp('2022-09-21 16:18:00'), 0],
 [Timestamp('2022-09-21 16:18:30'), 0],
 [Timestamp('2022-09-21 16:19:00'), 0],
 [Timestamp('2022-09-21 16:19:30'), 0],
 [Timestamp('2022-09-21 16:20:00'), 0],
 [Timestamp('2022-09-21 16:20:30'), 0],
 [Timestamp('2022-09-21 16:21:00'), 0],
 [Timestamp('2022-09-21 16:21:30'), 0],
 [Timestamp('2022-09-21 16:22:00'), 0],
 [Timestamp('2022-09-21 16:22:30'), 0],
 [Timestamp('2022-09-21 16:23:00'), 0],
 [Timestamp('2022-09-21 16:23:30'), 0],
 [Timestamp('2022-09-21 16:24:00'), 0],
 [Timestamp('2022-09-21 16:24:30'), 0],
 [Timestamp('2022-09-21 16:25:00'), 0],
 [Timestamp('2022-09-21 16:25:30'), 0],
 [Timestamp('2022-09-21 16:26:00'), 0],
 [Timestamp('2022-09-21 16:26:30'), 0],
 [Timestamp('2022-09-21 16:27:00'), 0],
 [Timestamp('2022-09-21 16:27:30'), 0],
 [Timestamp('2022-09-21 16:28:00'), 0],
 [Timestamp('2022-09-21 16:28:30'), 0],
 [Timestamp('2022-09-21 16:29:00'), 0],
 [Timestamp('2022-09-21 16:29:30'), 0],
 [Timestamp('2022-09-21 16:30:00'), 0],
 [Timestamp('2022-09-21 16:30:30'), 0],
 [Timestamp('2022-09-21 16:31:00'), 0],
 [Timestamp('2022-09-21 16:31:30'), 0],
 [Timestamp('2022-09-21 16:32:00'), 0],
 [Timestamp('2022-09-21 16:32:30'), 0],
 [Timestamp('2022-09-21 16:33:00'), 0],
 [Timestamp('2022-09-21 16:33:30'), 0],
 [Timestamp('2022-09-21 16:34:00'), 0],
 [Timestamp('2022-09-21 16:34:30'), 0],
 [Timestamp('2022-09-21 16:35:00'), 0],
 [Timestamp('2022-09-21 16:35:30'), 0],
 [Timestamp('2022-09-21 16:36:00'), 0],
 [Timestamp('2022-09-21 16:36:30'), 0],
 [Timestamp('2022-09-21 16:37:00'), 0],
 [Timestamp('2022-09-21 16:37:30'), 0],
 [Timestamp('2022-09-21 16:38:00'), 0],
 [Timestamp('2022-09-21 16:38:30'), 0],
 [Timestamp('2022-09-21 16:39:00'), 0],
 [Timestamp('2022-09-21 16:39:30'), 0],
 [Timestamp('2022-09-21 16:40:00'), 0],
 [Timestamp('2022-09-21 16:40:30'), 0],
 [Timestamp('2022-09-21 16:41:00'), 0],
 [Timestamp('2022-09-21 16:41:30'), 0],
 [Timestamp('2022-09-21 16:42:00'), 0],
 [Timestamp('2022-09-21 16:42:30'), 0],
 [Timestamp('2022-09-21 16:43:00'), 0],
 [Timestamp('2022-09-21 16:43:30'), 0],
 [Timestamp('2022-09-21 16:44:00'), 0],
 [Timestamp('2022-09-21 16:44:30'), 0],
 [Timestamp('2022-09-21 16:45:00'), 0],
 [Timestamp('2022-09-21 16:45:30'), 0],
 [Timestamp('2022-09-21 16:46:00'), 0],
 [Timestamp('2022-09-21 16:46:30'), 0],
 [Timestamp('2022-09-21 16:47:00'), 0],
 [Timestamp('2022-09-21 16:47:30'), 0],
 [Timestamp('2022-09-21 16:48:00'), 0],
 [Timestamp('2022-09-21 16:48:30'), 0],
 [Timestamp('2022-09-21 16:49:00'), 0],
 [Timestamp('2022-09-21 16:49:30'), 0],
 [Timestamp('2022-09-21 16:50:00'), 0],
 [Timestamp('2022-09-21 16:50:30'), 0],
 [Timestamp('2022-09-21 16:51:00'), 0],
 [Timestamp('2022-09-21 16:51:30'), 0],
 [Timestamp('2022-09-21 16:52:00'), 0],
 [Timestamp('2022-09-21 16:52:30'), 0],
 [Timestamp('2022-09-21 16:53:00'), 0],
 [Timestamp('2022-09-21 16:53:30'), 0],
 [Timestamp('2022-09-21 16:54:00'), 0],
 [Timestamp('2022-09-21 16:54:30'), 0],
 [Timestamp('2022-09-21 16:55:00'), 0],
 [Timestamp('2022-09-21 16:55:30'), 0],
 [Timestamp('2022-09-21 16:56:00'), 0],
 [Timestamp('2022-09-21 16:56:30'), 0],
 [Timestamp('2022-09-21 16:57:00'), 0],
 [Timestamp('2022-09-21 16:57:30'), 0],
 [Timestamp('2022-09-21 16:58:00'), 0],
 [Timestamp('2022-09-21 16:58:30'), 0],
 [Timestamp('2022-09-21 16:59:00'), 0],
 [Timestamp('2022-09-21 16:59:30'), 0],
 [Timestamp('2022-09-21 17:00:00'), 0],
 [Timestamp('2022-09-21 17:00:30'), 0],
 [Timestamp('2022-09-21 17:01:00'), 0],
 [Timestamp('2022-09-21 17:01:30'), 0],
 [Timestamp('2022-09-21 17:02:00'), 0],
 [Timestamp('2022-09-21 17:02:30'), 0],
 [Timestamp('2022-09-21 17:03:00'), 0],
 [Timestamp('2022-09-21 17:03:30'), 0],
 [Timestamp('2022-09-21 17:04:00'), 0],
 [Timestamp('2022-09-21 17:04:30'), 0],
 [Timestamp('2022-09-21 17:05:00'), 0],
 [Timestamp('2022-09-21 17:05:30'), 0],
 [Timestamp('2022-09-21 17:06:00'), 0],
 [Timestamp('2022-09-21 17:06:30'), 0],
 [Timestamp('2022-09-21 17:07:00'), 0],
 [Timestamp('2022-09-21 17:07:30'), 0],
 [Timestamp('2022-09-21 17:08:00'), 0],
 [Timestamp('2022-09-21 17:08:30'), 0],
 [Timestamp('2022-09-21 17:09:00'), 0],
 [Timestamp('2022-09-21 17:09:30'), 0],
 [Timestamp('2022-09-21 17:10:00'), 0],
 [Timestamp('2022-09-21 17:10:30'), 0],
 [Timestamp('2022-09-21 17:11:00'), 0],
 [Timestamp('2022-09-21 17:11:30'), 0],
 [Timestamp('2022-09-21 17:12:00'), 0],
 [Timestamp('2022-09-21 17:12:30'), 0],
 [Timestamp('2022-09-21 17:13:00'), 0],
 [Timestamp('2022-09-21 17:13:30'), 0],
 [Timestamp('2022-09-21 17:14:00'), 0],
 [Timestamp('2022-09-21 17:14:30'), 0],
 [Timestamp('2022-09-21 17:15:00'), 0],
 [Timestamp('2022-09-21 17:15:30'), 0],
 [Timestamp('2022-09-21 17:16:00'), 0],
 [Timestamp('2022-09-21 17:16:30'), 0],
 [Timestamp('2022-09-21 17:17:00'), 0],
 [Timestamp('2022-09-21 17:17:30'), 0],
 [Timestamp('2022-09-21 17:18:00'), 0],
 [Timestamp('2022-09-21 17:18:30'), 0],
 [Timestamp('2022-09-21 17:19:00'), 0],
 [Timestamp('2022-09-21 17:19:30'), 0],
 [Timestamp('2022-09-21 17:20:00'), 0],
 [Timestamp('2022-09-21 17:20:30'), 0],
 [Timestamp('2022-09-21 17:21:00'), 0],
 [Timestamp('2022-09-21 17:21:30'), 0],
 [Timestamp('2022-09-21 17:22:00'), 0],
 [Timestamp('2022-09-21 17:22:30'), 0],
 [Timestamp('2022-09-21 17:23:00'), 0],
 [Timestamp('2022-09-21 17:23:30'), 0],
 [Timestamp('2022-09-21 17:24:00'), 0],
 [Timestamp('2022-09-21 17:24:30'), 0],
 [Timestamp('2022-09-21 17:25:00'), 0],
 [Timestamp('2022-09-21 17:25:30'), 0],
 [Timestamp('2022-09-21 17:26:00'), 0],
 [Timestamp('2022-09-21 17:26:30'), 0],
 [Timestamp('2022-09-21 17:27:00'), 0],
 [Timestamp('2022-09-21 17:27:30'), 0],
 [Timestamp('2022-09-21 17:28:00'), 0],
 [Timestamp('2022-09-21 17:28:30'), 0],
 [Timestamp('2022-09-21 17:29:00'), 0],
 [Timestamp('2022-09-21 17:29:30'), 0],
 [Timestamp('2022-09-21 17:30:00'), 0],
 [Timestamp('2022-09-21 17:30:30'), 0],
 [Timestamp('2022-09-21 17:31:00'), 0],
 [Timestamp('2022-09-21 17:31:30'), 0],
 [Timestamp('2022-09-21 17:32:00'), 0],
 [Timestamp('2022-09-21 17:32:30'), 0],
 [Timestamp('2022-09-21 17:33:00'), 0],
 [Timestamp('2022-09-21 17:33:30'), 0],
 [Timestamp('2022-09-21 17:34:00'), 0],
 [Timestamp('2022-09-21 17:34:30'), 0],
 [Timestamp('2022-09-21 17:35:00'), 0],
 [Timestamp('2022-09-21 17:35:30'), 0],
 [Timestamp('2022-09-21 17:36:00'), 0],
 [Timestamp('2022-09-21 17:36:30'), 0],
 [Timestamp('2022-09-21 17:37:00'), 0],
 [Timestamp('2022-09-21 17:37:30'), 0],
 [Timestamp('2022-09-21 17:38:00'), 0],
 [Timestamp('2022-09-21 17:38:30'), 0],
 [Timestamp('2022-09-21 17:39:00'), 0],
 [Timestamp('2022-09-21 17:39:30'), 0],
 [Timestamp('2022-09-21 17:40:00'), 0],
 [Timestamp('2022-09-21 17:40:30'), 0],
 [Timestamp('2022-09-21 17:41:00'), 0],
 [Timestamp('2022-09-21 17:41:30'), 0],
 [Timestamp('2022-09-21 17:42:00'), 0],
 [Timestamp('2022-09-21 17:42:30'), 0],
 [Timestamp('2022-09-21 17:43:00'), 0],
 [Timestamp('2022-09-21 17:43:30'), 0],
 [Timestamp('2022-09-21 17:44:00'), 0],
 [Timestamp('2022-09-21 17:44:30'), 0],
 [Timestamp('2022-09-21 17:45:00'), 0],
 [Timestamp('2022-09-21 17:45:30'), 0],
 [Timestamp('2022-09-21 17:46:00'), 0],
 [Timestamp('2022-09-21 17:46:30'), 0],
 [Timestamp('2022-09-21 17:47:00'), 0],
 [Timestamp('2022-09-21 17:47:30'), 0],
 [Timestamp('2022-09-21 17:48:00'), 0],
 [Timestamp('2022-09-21 17:48:30'), 0],
 [Timestamp('2022-09-21 17:49:00'), 0],
 [Timestamp('2022-09-21 17:49:30'), 0],
 [Timestamp('2022-09-21 17:50:00'), 0],
 [Timestamp('2022-09-21 17:50:30'), 0],
 [Timestamp('2022-09-21 17:51:00'), 0],
 [Timestamp('2022-09-21 17:51:30'), 0],
 [Timestamp('2022-09-21 17:52:00'), 0],
 [Timestamp('2022-09-21 17:52:30'), 0],
 [Timestamp('2022-09-21 17:53:00'), 0],
 [Timestamp('2022-09-21 17:53:30'), 0],
 [Timestamp('2022-09-21 17:54:00'), 0],
 [Timestamp('2022-09-21 17:54:30'), 0],
 [Timestamp('2022-09-21 17:55:00'), 0],
 [Timestamp('2022-09-21 17:55:30'), 0],
 [Timestamp('2022-09-21 17:56:00'), 0],
 [Timestamp('2022-09-21 17:56:30'), 0],
 [Timestamp('2022-09-21 17:57:00'), 0],
 [Timestamp('2022-09-21 17:57:30'), 0],
 [Timestamp('2022-09-21 17:58:00'), 0],
 [Timestamp('2022-09-21 17:58:30'), 0],
 [Timestamp('2022-09-21 17:59:00'), 0],
 [Timestamp('2022-09-21 17:59:30'), 0],
 [Timestamp('2022-09-21 18:00:00'), 0],
 [Timestamp('2022-09-21 18:00:30'), 0],
 [Timestamp('2022-09-21 18:01:00'), 0],
 [Timestamp('2022-09-21 18:01:30'), 0],
 [Timestamp('2022-09-21 18:02:00'), 0],
 [Timestamp('2022-09-21 18:02:30'), 0],
 [Timestamp('2022-09-21 18:03:00'), 0],
 [Timestamp('2022-09-21 18:03:30'), 0],
 [Timestamp('2022-09-21 18:04:00'), 0],
 [Timestamp('2022-09-21 18:04:30'), 0],
 [Timestamp('2022-09-21 18:05:00'), 0],
 [Timestamp('2022-09-21 18:05:30'), 0],
 [Timestamp('2022-09-21 18:06:00'), 0],
 [Timestamp('2022-09-21 18:06:30'), 0],
 [Timestamp('2022-09-21 18:07:00'), 0],
 [Timestamp('2022-09-21 18:07:30'), 0],
 [Timestamp('2022-09-21 18:08:00'), 0],
 [Timestamp('2022-09-21 18:08:30'), 0],
 [Timestamp('2022-09-21 18:09:00'), 0],
 [Timestamp('2022-09-21 18:09:30'), 0],
 [Timestamp('2022-09-21 18:10:00'), 0],
 [Timestamp('2022-09-21 18:10:30'), 0],
 [Timestamp('2022-09-21 18:11:00'), 0],
 [Timestamp('2022-09-21 18:11:30'), 0],
 [Timestamp('2022-09-21 18:12:00'), 0],
 [Timestamp('2022-09-21 18:12:30'), 0],
 [Timestamp('2022-09-21 18:13:00'), 0],
 [Timestamp('2022-09-21 18:13:30'), 0],
 [Timestamp('2022-09-21 18:14:00'), 0],
 [Timestamp('2022-09-21 18:14:30'), 0],
 [Timestamp('2022-09-21 18:15:00'), 0],
 [Timestamp('2022-09-21 18:15:30'), 0],
 [Timestamp('2022-09-21 18:16:00'), 0],
 [Timestamp('2022-09-21 18:16:30'), 0],
 [Timestamp('2022-09-21 18:17:00'), 0],
 [Timestamp('2022-09-21 18:17:30'), 0],
 [Timestamp('2022-09-21 18:18:00'), 0],
 [Timestamp('2022-09-21 18:18:30'), 0],
 [Timestamp('2022-09-21 18:19:00'), 0],
 [Timestamp('2022-09-21 18:19:30'), 0],
 [Timestamp('2022-09-21 18:20:00'), 0],
 [Timestamp('2022-09-21 18:20:30'), 0],
 [Timestamp('2022-09-21 18:21:00'), 0],
 [Timestamp('2022-09-21 18:21:30'), 0],
 [Timestamp('2022-09-21 18:22:00'), 0],
 [Timestamp('2022-09-21 18:22:30'), 0],
 [Timestamp('2022-09-21 18:23:00'), 0],
 [Timestamp('2022-09-21 18:23:30'), 0],
 [Timestamp('2022-09-21 18:24:00'), 0],
 [Timestamp('2022-09-21 18:24:30'), 0],
 [Timestamp('2022-09-21 18:25:00'), 0],
 [Timestamp('2022-09-21 18:25:30'), 0],
 [Timestamp('2022-09-21 18:26:00'), 0],
 [Timestamp('2022-09-21 18:26:30'), 0],
 [Timestamp('2022-09-21 18:27:00'), 0],
 [Timestamp('2022-09-21 18:27:30'), 0],
 [Timestamp('2022-09-21 18:28:00'), 0],
 [Timestamp('2022-09-21 18:28:30'), 0],
 [Timestamp('2022-09-21 18:29:00'), 0],
 [Timestamp('2022-09-21 18:29:30'), 0],
 [Timestamp('2022-09-21 18:30:00'), 0],
 [Timestamp('2022-09-21 18:30:30'), 0],
 [Timestamp('2022-09-21 18:31:00'), 0],
 [Timestamp('2022-09-21 18:31:30'), 0],
 [Timestamp('2022-09-21 18:32:00'), 0],
 [Timestamp('2022-09-21 18:32:30'), 0],
 [Timestamp('2022-09-21 18:33:00'), 0],
 [Timestamp('2022-09-21 18:33:30'), 0],
 [Timestamp('2022-09-21 18:34:00'), 0],
 [Timestamp('2022-09-21 18:34:30'), 0],
 [Timestamp('2022-09-21 18:35:00'), 0],
 [Timestamp('2022-09-21 18:35:30'), 0],
 [Timestamp('2022-09-21 18:36:00'), 0],
 [Timestamp('2022-09-21 18:36:30'), 0],
 [Timestamp('2022-09-21 18:37:00'), 0],
 [Timestamp('2022-09-21 18:37:30'), 0],
 [Timestamp('2022-09-21 18:38:00'), 0],
 [Timestamp('2022-09-21 18:38:30'), 0],
 [Timestamp('2022-09-21 18:39:00'), 0],
 [Timestamp('2022-09-21 18:39:30'), 0],
 [Timestamp('2022-09-21 18:40:00'), 0],
 [Timestamp('2022-09-21 18:40:30'), 0],
 [Timestamp('2022-09-21 18:41:00'), 0],
 [Timestamp('2022-09-21 18:41:30'), 0],
 [Timestamp('2022-09-21 18:42:00'), 0],
 [Timestamp('2022-09-21 18:42:30'), 0],
 [Timestamp('2022-09-21 18:43:00'), 0],
 [Timestamp('2022-09-21 18:43:30'), 0],
 [Timestamp('2022-09-21 18:44:00'), 0],
 [Timestamp('2022-09-21 18:44:30'), 0],
 [Timestamp('2022-09-21 18:45:00'), 0],
 [Timestamp('2022-09-21 18:45:30'), 0],
 [Timestamp('2022-09-21 18:46:00'), 0],
 [Timestamp('2022-09-21 18:46:30'), 0],
 [Timestamp('2022-09-21 18:47:00'), 0],
 [Timestamp('2022-09-21 18:47:30'), 0],
 [Timestamp('2022-09-21 18:48:00'), 0],
 [Timestamp('2022-09-21 18:48:30'), 0],
 [Timestamp('2022-09-21 18:49:00'), 0],
 [Timestamp('2022-09-21 18:49:30'), 0],
 [Timestamp('2022-09-21 18:50:00'), 0],
 [Timestamp('2022-09-21 18:50:30'), 0],
 [Timestamp('2022-09-21 18:51:00'), 0],
 [Timestamp('2022-09-21 18:51:30'), 0],
 [Timestamp('2022-09-21 18:52:00'), 0],
 [Timestamp('2022-09-21 18:52:30'), 0],
 [Timestamp('2022-09-21 18:53:00'), 0],
 [Timestamp('2022-09-21 18:53:30'), 0],
 [Timestamp('2022-09-21 18:54:00'), 0],
 [Timestamp('2022-09-21 18:54:30'), 0],
 [Timestamp('2022-09-21 18:55:00'), 0],
 [Timestamp('2022-09-21 18:55:30'), 0],
 [Timestamp('2022-09-21 18:56:00'), 0],
 [Timestamp('2022-09-21 18:56:30'), 0],
 [Timestamp('2022-09-21 18:57:00'), 0],
 [Timestamp('2022-09-21 18:57:30'), 0],
 [Timestamp('2022-09-21 18:58:00'), 0],
 [Timestamp('2022-09-21 18:58:30'), 0],
 [Timestamp('2022-09-21 18:59:00'), 0],
 [Timestamp('2022-09-21 18:59:30'), 0],
 [Timestamp('2022-09-21 19:00:00'), 0],
 [Timestamp('2022-09-21 19:00:30'), 0],
 [Timestamp('2022-09-21 19:01:00'), 0],
 [Timestamp('2022-09-21 19:01:30'), 0],
 [Timestamp('2022-09-21 19:02:00'), 0],
 [Timestamp('2022-09-21 19:02:30'), 0],
 [Timestamp('2022-09-21 19:03:00'), 0],
 [Timestamp('2022-09-21 19:03:30'), 0],
 [Timestamp('2022-09-21 19:04:00'), 0],
 [Timestamp('2022-09-21 19:04:30'), 0],
 [Timestamp('2022-09-21 19:05:00'), 0],
 [Timestamp('2022-09-21 19:05:30'), 0],
 [Timestamp('2022-09-21 19:06:00'), 0],
 [Timestamp('2022-09-21 19:06:30'), 0],
 [Timestamp('2022-09-21 19:07:00'), 0],
 [Timestamp('2022-09-21 19:07:30'), 0],
 [Timestamp('2022-09-21 19:08:00'), 0],
 [Timestamp('2022-09-21 19:08:30'), 0],
 [Timestamp('2022-09-21 19:09:00'), 0],
 [Timestamp('2022-09-21 19:09:30'), 0],
 [Timestamp('2022-09-21 19:10:00'), 0],
 [Timestamp('2022-09-21 19:10:30'), 0],
 [Timestamp('2022-09-21 19:11:00'), 0],
 [Timestamp('2022-09-21 19:11:30'), 0],
 [Timestamp('2022-09-21 19:12:00'), 0],
 [Timestamp('2022-09-21 19:12:30'), 0],
 [Timestamp('2022-09-21 19:13:00'), 0],
 [Timestamp('2022-09-21 19:13:30'), 0],
 [Timestamp('2022-09-21 19:14:00'), 0],
 [Timestamp('2022-09-21 19:14:30'), 0],
 [Timestamp('2022-09-21 19:15:00'), 0],
 [Timestamp('2022-09-21 19:15:30'), 0],
 [Timestamp('2022-09-21 19:16:00'), 0],
 [Timestamp('2022-09-21 19:16:30'), 0],
 [Timestamp('2022-09-21 19:17:00'), 0],
 [Timestamp('2022-09-21 19:17:30'), 0],
 [Timestamp('2022-09-21 19:18:00'), 0],
 [Timestamp('2022-09-21 19:18:30'), 0],
 [Timestamp('2022-09-21 19:19:00'), 0],
 [Timestamp('2022-09-21 19:19:30'), 0],
 [Timestamp('2022-09-21 19:20:00'), 0],
 [Timestamp('2022-09-21 19:20:30'), 0],
 [Timestamp('2022-09-21 19:21:00'), 0],
 [Timestamp('2022-09-21 19:21:30'), 0],
 [Timestamp('2022-09-21 19:22:00'), 0],
 [Timestamp('2022-09-21 19:22:30'), 0],
 [Timestamp('2022-09-21 19:23:00'), 0],
 [Timestamp('2022-09-21 19:23:30'), 0],
 [Timestamp('2022-09-21 19:24:00'), 0],
 [Timestamp('2022-09-21 19:24:30'), 0],
 [Timestamp('2022-09-21 19:25:00'), 0],
 [Timestamp('2022-09-21 19:25:30'), 0],
 [Timestamp('2022-09-21 19:26:00'), 0],
 [Timestamp('2022-09-21 19:26:30'), 0],
 [Timestamp('2022-09-21 19:27:00'), 0],
 [Timestamp('2022-09-21 19:27:30'), 0],
 [Timestamp('2022-09-21 19:28:00'), 0],
 [Timestamp('2022-09-21 19:28:30'), 0],
 [Timestamp('2022-09-21 19:29:00'), 0],
 [Timestamp('2022-09-21 19:29:30'), 0],
 [Timestamp('2022-09-21 19:30:00'), 0],
 [Timestamp('2022-09-21 19:30:30'), 0],
 [Timestamp('2022-09-21 19:31:00'), 0],
 [Timestamp('2022-09-21 19:31:30'), 0],
 [Timestamp('2022-09-21 19:32:00'), 0],
 [Timestamp('2022-09-21 19:32:30'), 0],
 [Timestamp('2022-09-21 19:33:00'), 0],
 [Timestamp('2022-09-21 19:33:30'), 0],
 [Timestamp('2022-09-21 19:34:00'), 0],
 [Timestamp('2022-09-21 19:34:30'), 0],
 [Timestamp('2022-09-21 19:35:00'), 0],
 [Timestamp('2022-09-21 19:35:30'), 0],
 [Timestamp('2022-09-21 19:36:00'), 0],
 [Timestamp('2022-09-21 19:36:30'), 0],
 [Timestamp('2022-09-21 19:37:00'), 0],
 [Timestamp('2022-09-21 19:37:30'), 0],
 [Timestamp('2022-09-21 19:38:00'), 0],
 [Timestamp('2022-09-21 19:38:30'), 0],
 [Timestamp('2022-09-21 19:39:00'), 0],
 [Timestamp('2022-09-21 19:39:30'), 0],
 [Timestamp('2022-09-21 19:40:00'), 0],
 [Timestamp('2022-09-21 19:40:30'), 0],
 [Timestamp('2022-09-21 19:41:00'), 0],
 [Timestamp('2022-09-21 19:41:30'), 0],
 [Timestamp('2022-09-21 19:42:00'), 0],
 [Timestamp('2022-09-21 19:42:30'), 0],
 [Timestamp('2022-09-21 19:43:00'), 0],
 [Timestamp('2022-09-21 19:43:30'), 0],
 [Timestamp('2022-09-21 19:44:00'), 0],
 [Timestamp('2022-09-21 19:44:30'), 0],
 [Timestamp('2022-09-21 19:45:00'), 0],
 [Timestamp('2022-09-21 19:45:30'), 0],
 [Timestamp('2022-09-21 19:46:00'), 0],
 [Timestamp('2022-09-21 19:46:30'), 0],
 [Timestamp('2022-09-21 19:47:00'), 0],
 [Timestamp('2022-09-21 19:47:30'), 0],
 [Timestamp('2022-09-21 19:48:00'), 0],
 [Timestamp('2022-09-21 19:48:30'), 0],
 [Timestamp('2022-09-21 19:49:00'), 0],
 [Timestamp('2022-09-21 19:49:30'), 0],
 [Timestamp('2022-09-21 19:50:00'), 0],
 [Timestamp('2022-09-21 19:50:30'), 0],
 [Timestamp('2022-09-21 19:51:00'), 0],
 [Timestamp('2022-09-21 19:51:30'), 0],
 [Timestamp('2022-09-21 19:52:00'), 0],
 [Timestamp('2022-09-21 19:52:30'), 0],
 [Timestamp('2022-09-21 19:53:00'), 0],
 [Timestamp('2022-09-21 19:53:30'), 0],
 [Timestamp('2022-09-21 19:54:00'), 0],
 [Timestamp('2022-09-21 19:54:30'), 0],
 [Timestamp('2022-09-21 19:55:00'), 0],
 [Timestamp('2022-09-21 19:55:30'), 0],
 [Timestamp('2022-09-21 19:56:00'), 0],
 [Timestamp('2022-09-21 19:56:30'), 0],
 [Timestamp('2022-09-21 19:57:00'), 0],
 [Timestamp('2022-09-21 19:57:30'), 0],
 [Timestamp('2022-09-21 19:58:00'), 0],
 [Timestamp('2022-09-21 19:58:30'), 0],
 [Timestamp('2022-09-21 19:59:00'), 0],
 [Timestamp('2022-09-21 19:59:30'), 0],
 [Timestamp('2022-09-21 20:00:00'), 0],
 [Timestamp('2022-09-21 20:00:30'), 0],
 [Timestamp('2022-09-21 20:01:00'), 0],
 [Timestamp('2022-09-21 20:01:30'), 0],
 [Timestamp('2022-09-21 20:02:00'), 0],
 [Timestamp('2022-09-21 20:02:30'), 0],
 [Timestamp('2022-09-21 20:03:00'), 0],
 [Timestamp('2022-09-21 20:03:30'), 0],
 [Timestamp('2022-09-21 20:04:00'), 0],
 [Timestamp('2022-09-21 20:04:30'), 0],
 [Timestamp('2022-09-21 20:05:00'), 0],
 [Timestamp('2022-09-21 20:05:30'), 0],
 [Timestamp('2022-09-21 20:06:00'), 0],
 [Timestamp('2022-09-21 20:06:30'), 0],
 [Timestamp('2022-09-21 20:07:00'), 0],
 [Timestamp('2022-09-21 20:07:30'), 0],
 [Timestamp('2022-09-21 20:08:00'), 0],
 [Timestamp('2022-09-21 20:08:30'), 0],
 [Timestamp('2022-09-21 20:09:00'), 0],
 [Timestamp('2022-09-21 20:09:30'), 0],
 [Timestamp('2022-09-21 20:10:00'), 0],
 [Timestamp('2022-09-21 20:10:30'), 0],
 [Timestamp('2022-09-21 20:11:00'), 0],
 [Timestamp('2022-09-21 20:11:30'), 0],
 [Timestamp('2022-09-21 20:12:00'), 0],
 [Timestamp('2022-09-21 20:12:30'), 0],
 [Timestamp('2022-09-21 20:13:00'), 0],
 [Timestamp('2022-09-21 20:13:30'), 0],
 [Timestamp('2022-09-21 20:14:00'), 0],
 [Timestamp('2022-09-21 20:14:30'), 0],

Fragmentation Index: The sum of the ‘Mobile time (%)’ and the ‘Immobile bouts <=1min (%)’. This is an indication of the degree of fragmentation of the sleep period, and can be used as an indication of sleep quality (or the lack of it).

In [ ]:
# Sample data for sleep_period and sleep_scori
sleep_period = pd.DataFrame(sleep_period_list, columns=['start_datetime', 'end_datetime'])
sleep_scoring = pd.DataFrame(sleep_scoring_list, columns=['datetime', 'score'])

# Convert datetime columns to datetime format
sleep_period['start_datetime'] = pd.to_datetime(sleep_period['start_datetime'])
sleep_period['end_datetime'] = pd.to_datetime(sleep_period['end_datetime'])
sleep_scoring['datetime'] = pd.to_datetime(sleep_scoring['datetime'])

# Initialize a list to store the results
results = []

# Calculate the amount of epochs scored as 0 for each sleep period
for i in range(len(sleep_period)):
    start = sleep_period['start_datetime'][i]
    end = sleep_period['end_datetime'][i]
    mask = (sleep_scoring['datetime'] >= start) & (sleep_scoring['datetime'] <= end)
    results.append(sleep_scoring.loc[mask, 'score'].value_counts().get(0, 0))

# Add the results to the sleep_period dataframe
sleep_period['score_0'] = results

-------------------------------------------------

In [ ]:
df_FI = pd.read_excel(fpath + '\\fragmentation_indices.xlsx')

In [ ]:
# in df_FI add one day to the column 'Date' 
df_FI['Date'] = df_FI['Date'] + pd.DateOffset(days=1)

In [ ]:
df_FI.rename(columns={'Date':'date'}, inplace=True)

In [ ]:
df_FI.drop('Unnamed: 0', axis=1, inplace=True)

In [ ]:
# merge the two dataframes according to the column 'Date'
df_merged = pd.merge(df, df_FI, on='date', how='left')

In [ ]:
df_merged.to_excel(fpath + '\\6.0_database_variables.xlsx', index=False)